import React, { useState } from 'react';
import { Globe, AlertTriangle, DatabaseZap, ChevronRight } from 'lucide-react';
import { RiskCardData } from '../types';

export const RiskTopology: React.FC = () => {
  const [selectedRisk, setSelectedRisk] = useState<RiskCardData | null>(null);

  const riskCards: RiskCardData[] = [
    {
      id: 'polarization',
      title: 'Polarization Escalation',
      severity: 'Critical Threat',
      severityClass: 'bg-[#9E382A] text-[#F9F7F2]',
      badgeClass: 'text-[#9E382A]',
      icon: 'globe',
      description:
        'Model attention weights systematically reward hyperbolic conflict, severely degrading exposure to nuance or consensus datasets.',
      technicalDetails:
        'Cosine similarity clustering in 1536-dimensional latent space splits user representations into discrete ideological extrema, penalizing centrist semantic bridges.',
      impactScore: 88,
      realWorldExample:
        'Automated ranking engines increasing click-through by 312% when headlines utilize combative vocabulary over reconciliatory phrasing.',
    },
    {
      id: 'fear',
      title: 'Perceptual Distortion',
      severity: 'Systemic Risk',
      severityClass: 'bg-[#A37B5C] text-[#F9F7F2]',
      badgeClass: 'text-[#A37B5C]',
      icon: 'warning',
      description:
        'Threat-detection heuristics misclassify neutral ambiguous discourse as hostile, generating paranoid and defensive operational logic.',
      technicalDetails:
        'False positive rate in semantic toxicity classifiers shifts from 4.1% to 27.9% after 5 recursive training cycles on uncalibrated report telemetry.',
      impactScore: 96,
      realWorldExample:
        'Autonomous moderation models flagging historical academic discourse regarding conflict as contemporary threat vectors.',
    },
    {
      id: 'degradation',
      title: 'Model Autophagy (MAD)',
      severity: 'Corpus Entropy',
      severityClass: 'bg-[#1A1A1A] text-[#F9F7F2]',
      badgeClass: 'text-[#1A1A1A]',
      icon: 'database',
      description:
        'Continuous feedback loops contaminate downstream training sets with synthetic pessimistic artifacts generated by prior generation models.',
      technicalDetails:
        'Model Autophagy Disorder: Synthetic corpora suffer severe variance collapse, compounding cynical linguistic tokens exponentially over iterations.',
      impactScore: 74,
      realWorldExample:
        'LLM-generated synthetic web text skewing subsequent base model checkpoints toward pervasive existential fatalism.',
    },
  ];

  return (
    <section id="risks" className="flex flex-col gap-8 scroll-mt-24 border-b border-[#1A1A1A]/10 pb-16">
      {/* Section Title */}
      <div className="flex flex-col gap-3">
        <div className="flex items-center gap-3">
          <div className="h-[1px] w-8 bg-[#1A1A1A]/40"></div>
          <span className="text-[10px] uppercase tracking-[0.25em] font-sans font-bold text-[#A37B5C]">
            Section 03 // Failure Topologies
          </span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-serif font-normal text-[#1A1A1A] tracking-tight">
          Systemic Risk <span className="italic font-normal">Topology.</span>
        </h2>
        <p className="font-serif text-base sm:text-lg text-[#1A1A1A]/75 max-w-3xl leading-relaxed">
          When left unchecked, structural negativity bias cascades across model checkpoints, creating multi-system epistemic drift and compounding societal alienation.
        </p>
      </div>

      {/* 3 Grid Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {riskCards.map((card, idx) => {
          return (
            <div
              key={card.id}
              id={`risk-card-${card.id}`}
              onClick={() => setSelectedRisk(card)}
              className="bg-[#FFFFFF] border border-[#1A1A1A]/15 p-6 sm:p-7 flex flex-col justify-between group hover:border-[#1A1A1A] transition-all duration-300 cursor-pointer shadow-[0_2px_12px_rgba(26,26,26,0.03)]"
            >
              <div>
                {/* Header with Icon and Severity Badge */}
                <div className="flex justify-between items-start border-b border-[#1A1A1A]/10 pb-4 mb-4">
                  <span className="text-[10px] uppercase font-sans font-bold tracking-[0.2em] text-[#66635B]">
                    Plate 03.{idx + 1}
                  </span>

                  <div className={`font-sans text-[9px] uppercase tracking-widest px-2.5 py-1 font-bold ${card.severityClass}`}>
                    {card.severity}
                  </div>
                </div>

                {/* Title & Description */}
                <h3 className="text-2xl font-serif text-[#1A1A1A] group-hover:text-[#A37B5C] transition-colors mb-3">
                  {card.title}
                </h3>
                <p className="font-serif text-sm text-[#1A1A1A]/75 leading-relaxed mb-6">
                  {card.description}
                </p>
              </div>

              <div>
                {/* Impact score bar */}
                <div className="pt-4 border-t border-[#1A1A1A]/10 flex flex-col gap-1.5 mb-4">
                  <div className="flex justify-between text-[10px] uppercase font-sans tracking-widest text-[#66635B]">
                    <span>Latent Cascade Impact</span>
                    <span className="font-serif font-bold text-[#1A1A1A] text-xs">{card.impactScore}/100</span>
                  </div>
                  <div className="w-full h-1 bg-[#EAE6DC] overflow-hidden">
                    <div
                      className="h-full transition-all duration-500 bg-[#1A1A1A]"
                      style={{ width: `${card.impactScore}%` }}
                    />
                  </div>
                </div>

                <div className="flex items-center gap-1 text-[10px] uppercase font-sans tracking-wider font-bold text-[#1A1A1A] group-hover:translate-x-1 transition-transform">
                  <span>Examine Dossier</span>
                  <ChevronRight className="w-3.5 h-3.5 text-[#A37B5C]" />
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Selected Risk Details Modal / Archival Dossier */}
      {selectedRisk && (
        <div
          id="risk-detail-overlay"
          className="fixed inset-0 z-50 bg-[#1A1A1A]/70 backdrop-blur-xs flex items-center justify-center p-4"
          onClick={() => setSelectedRisk(null)}
        >
          <div
            className="bg-[#F9F7F2] p-8 sm:p-10 max-w-2xl w-full border border-[#1A1A1A] shadow-2xl flex flex-col gap-6"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex justify-between items-start border-b border-[#1A1A1A]/15 pb-4">
              <div>
                <span className="text-[10px] uppercase font-sans font-bold tracking-[0.25em] text-[#A37B5C]">
                  Risk Diagnosis &amp; Telemetry Vector
                </span>
                <h3 className="text-3xl font-serif text-[#1A1A1A] mt-1">
                  {selectedRisk.title}
                </h3>
              </div>
              <span className={`font-sans text-[10px] uppercase tracking-widest px-3 py-1 font-bold ${selectedRisk.severityClass}`}>
                {selectedRisk.severity}
              </span>
            </div>

            <div className="flex flex-col gap-5 text-[#1A1A1A]">
              <div className="p-4 bg-[#EAE6DC] border-l-2 border-[#1A1A1A] font-serif text-base text-[#1A1A1A]/85 leading-relaxed">
                {selectedRisk.description}
              </div>

              <div>
                <strong className="text-[#1A1A1A] block mb-1 font-sans text-[10px] uppercase tracking-widest font-bold">
                  Mathematical / Latent Mechanism:
                </strong>
                <p className="font-mono text-xs bg-[#FFFFFF] p-3 border border-[#1A1A1A]/10 text-[#1A1A1A]/90 leading-relaxed">
                  {selectedRisk.technicalDetails}
                </p>
              </div>

              <div>
                <strong className="text-[#9E382A] block mb-1 font-sans text-[10px] uppercase tracking-widest font-bold">
                  Empirical Case Study:
                </strong>
                <p className="font-serif text-sm bg-[#FFFFFF] p-3 border border-[#1A1A1A]/10 text-[#1A1A1A]/80 leading-relaxed">
                  {selectedRisk.realWorldExample}
                </p>
              </div>
            </div>

            <div className="flex justify-end gap-3 pt-4 border-t border-[#1A1A1A]/15">
              <button
                onClick={() => setSelectedRisk(null)}
                className="px-6 py-2.5 bg-[#1A1A1A] hover:bg-[#333333] text-[#F9F7F2] font-sans text-xs uppercase tracking-widest font-bold cursor-pointer transition-all active:scale-95"
              >
                Close Dossier
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  );
};
